### ISSUE TITLE
send token error

### ISSUE THREAD

**Issue by idimon4uk** [blockxlabs/aiwa#12]
Before filing a new issue, please provide the following information.

#### AIWA version
1.0
![image](https://user-images.githubusercontent.com/16037887/50978330-e05cc100-14fc-11e9-9319-f7bf8f3260b9.png)

#### Installed from Chrome Web Store or Github release?
from web store

#### Chrome version?
Version 71.0.3578.98 (Official Build) (64-bit)

#### OS and version?
Ubuntu 18.04

#### Which provider are you using?
Mastery 

#### Steps to reproduce
I tried send some my own tokens to my other address.
I use ATS of smart contract.
I switched my tokens to AION in plugin` window
![image](https://user-images.githubusercontent.com/16037887/50979036-5c0b3d80-14fe-11e9-8f6f-cc27c4962628.png)
and tried send 50 TAT3 tokens to other address
![image](https://user-images.githubusercontent.com/16037887/50979136-8c52dc00-14fe-11e9-9ee7-bf6edc036258.png)
but i have enough amount
temp1 - is contract instance (contract address 0xa07224c14B2144A38a9B840815A414DcE8FC0e2F226bD4e676DAD7621172d868)
I switched to TAT3 tokens 
![image](https://user-images.githubusercontent.com/16037887/50979375-008d7f80-14ff-11e9-8fc3-0d996aac9fca.png)
and tried again
![image](https://user-images.githubusercontent.com/16037887/50979522-54986400-14ff-11e9-82f3-4f348d76cf67.png)
when i tried 'send' this transaction i received
![image](https://user-images.githubusercontent.com/16037887/50979713-c2449000-14ff-11e9-9966-ecc19089bf66.png)

#### Code snippets/screenshots (if not in above questions)
smart contract send function
![image](https://user-images.githubusercontent.com/16037887/50979816-fae46980-14ff-11e9-8e71-00cddef84b30.png)
init contract 
>>
const contract = aionweb3.eth.contract(abi_ercATS).at(address)
const txHash = yield contract.send(tx.tx.userAddress, tx.tx.amountToSend,0);
<<

**Comment by jonpurdy** [comment]
@idimon4uk could you let us know if this is still an issue with 1.1? Much thanks.

**Comment by idimon4uk** [comment]
@jonpurdy When I checking aiwa last time , everything was ok! I'll reopen issue if I reproduce this again! Thanks for work!
