### ISSUE TITLE
aiwa contract instantiation not working

### ISSUE THREAD

**Issue by lazaridiscom** [blockxlabs/aiwa#16]
This line should work, but it raises an error:

```js
myContract = new aiwa.eth.Contract(casinoJSON.info.abiDefinition, contractAddress);

# ERROR: aiwa.eth.Contract is not a constructor
```

The same happens with the existent code:

```js
myContract = new aiwa.Contract(casinoJSON.info.abiDefinition, contractAddress);

# ERROR: aiwa.Contract is not a constructor
```

## Reproduction

just move the contract-creation into the onload event to see the error.

(example: https://github.com/aion-kimcodeashian/aion-roulette)

## AIWA Source-Code

The AIWA source-code is not public (https://github.com/blockxlabs/aiwa/issues/13), and I start to wonder what all this is about.

Quite alienating experience.

**Comment by kushptlapigarage** [comment]
@lazaridiscom As Error suggests `ERROR: aiwa.Contract is not a constructor`. Remove `new` keyword.

Follow the *Sample DApp*  at https://github.com/blockxlabs/aiwa/blob/master/sample-dapp/index.js#L4. That's official and test by Aiwa devs.

**Comment by lazaridiscom** [comment]
thanks for the pointer, this should work as a workaround(!!!).

But the official way is the snippet I gave, see:

https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html

Thus

```js
myContract = new aiwa.eth.Contract(casinoJSON.info.abiDefinition, contractAddress);
```
must work.

.

**Comment by kushptlapigarage** [comment]
Closing the issue.

**Comment by lazaridiscom** [comment]
Why do you close this?

AIWA's implementation is currently incompatible with existent web3 api.
