### ISSUE TITLE
Product website opens automatically when new versions are available

### ISSUE THREAD

**Issue by ToJen** [blockxlabs/aiwa#19]
Before filing a new issue, please provide the following information.

#### AIWA version
1.2

#### Installed from Chrome Web Store or Github release?
web store

#### Chrome version?
72.0.3626.109 (Official Build) (64-bit)

#### OS and version?
Ubuntu 16.04

#### Any additional information or details?
The aiwa homepage opens up when new versions are available on Chrome.

**Comment by JesseAbram** [comment]
This is expected behaviour but if we see a lot of down votes we will move it to feature.
