### ISSUE TITLE
aionweb3.currentProvider keeps defaulting back to localhost

### ISSUE THREAD

**Issue by jonathanjm** [blockxlabs/aiwa#2]
When I change the provider in the wallet to let's say 'Mainnet', aionweb3.currentProvider is set to "https://api.nodesmith.io/v1/aion/mainnet/jsonrpc?apiKey=85268e8181c74b249a93581a8cb9c213" but if I refresh the page, aionweb3.currentProvider is set to http://127.0.0.1:8545

**Comment by jonpurdy-blockxlabs** [comment]
This has been fixed in 0.1.2.
