### ISSUE TITLE
AIWA not injecting `aionweb3` into local webpages.

### ISSUE THREAD

**Issue by mohnjatthews** [blockxlabs/aiwa#23]
#### AIWA version
1.2

#### Installed from Chrome Web Store or Github release?
Web Store

#### Chrome version?
72.0.3626.121 (Official Build) (64-bit)

#### OS and version?
MacOS 10.14.3 (18D42)

#### Which provider are you using?
Irrelevant to problem

#### Expected vs actual behaviour
When looking at a local webpage I want AIWA to inject the `aionweb3` variable into the page.

This doesn't happen. I get:

```
aionweb3
Uncaught ReferenceError: aionweb3 is not defined
    at <anonymous>:1:1
```

But when I go to [example.com](http://example.com/) I get:

```
aionweb3
Proxy {_requestManager: c, currentProvider: i, eth: y, db: t.exports, shh: c, …}
```

#### Steps to reproduce

1. Create this file and name it `test.html`:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Example Page</title>
</head>

<body>
</body>

</html>
```

2. Open the file in a browser.
3. Open the console and enter `aionweb3`.

**Comment by dhruvinparikh93** [comment]
@mohnjatthews 

### Steps to solve :

- Open Chrome. 
- Goto : `chrome://flags/#allow-insecure-localhost` 
- Enable the flag showed in screen shot.

![image](https://user-images.githubusercontent.com/29928916/54054533-6ec98800-41b8-11e9-832b-ea940db6cec6.png)

**Comment by dhruvinparikh93** [comment]
My last comment is not the actual solution. I misunderstood your issue.

Here are the steps I tried to verify `aionweb3` injection on `localhost`.

*Steps*
- open terminal and run below commands
```
$ npm install -g serve
$ serve
```
- Open Chrome and go to `localhost:5000` or URL presented by serve command's output
- Open console in Chrome and type _aionweb3_

We see
```
aionweb3
Proxy {_requestManager: c, currentProvider: i, eth: y, db: t.exports, shh: c, …}
```

**Comment by mohnjatthews** [comment]
Sorry for the delay in relpying, was at the UofT hackathon all weekend. Your second comment worked perfectly!
