### ISSUE TITLE
AIWA doesn't open.

### ISSUE THREAD

**Issue by johnnymatthews** [blockxlabs/aiwa#25]
#### AIWA version

1.2

#### Installed from Chrome Web Store or Github release?

Web Store

#### Chrome version?

73.0.3683.103 (Official Build) (64-bit)

#### OS and version?

MacOS 10.14.3 (18D109)

#### Which provider are you using?

Irrelevant to problem

#### Expected vs actual behaviour

Expected: AIWA opens when clicked.

Actual: AIWA either doesn't open at all, or take a long time to open.

#### Steps to reproduce

I can't narrow down the issue. Sometimes it happens when I first open the extension. Sometimes it happens after using it for a while. Sometimes it happens after changing networks. Sometimes it happens after changing wallets.

### More Info

Other apps like LastPass, Ad Blocker, Metamask, all open as soon as they are clicked. AIWA, if it opens at all, takes a substantial amount of time to open.

The only _fix_ I can find is completely closing Chrome and re-opening. When that doesn't work, completely removing AIWA, re-installing, closing Chrome and re-opening sometimes helps.

**Comment by kushptlapigarage** [comment]
I have Aiwa installed on 72.0.3626.121 Chrome, Mac, and did a good run around Aiwa. I couldn't reproduce the issue you are suggesting.

I will inform fellow devs to keep and eye on Aiwa's performance and also keep this issue alive to get more feedback.

**Comment by mohnjatthews** [comment]
Are there any logs available that I can forward to you guys when it next happens again?

**Comment by kushptlapigarage** [comment]
I can definitely look at the logs.

 I am going to upgrade chrome, reinstall AIWA and see if I can replicate.

**Comment by mohnjatthews** [comment]
I'm able to consistently reproduce the issue by doing this:

1. Open Chrome & AIWA.
2. Change to a custom network. 
3. Enter a remote node URL.
4. Enter an incorrect port number: `123` for example.

AIWA then completely crashes and doesn't open unless Chrome is completely closed and reopened.
