### ISSUE TITLE
Log out support/Multi vault or wallet management support

### ISSUE THREAD

**Issue by stevebayerin** [blockxlabs/aiwa#27]
Before filing a new issue, please provide the following information.

#### AIWA version
1.2

#### Installed from Chrome Web Store or Github release?
web store

#### Chrome version?
74.0.3729.131

#### OS and version?
Windows 10 Education Version, last updated on 9/May/2019

#### Which provider are you using?
Mainnet

#### Expected vs actual behaviour

Expected: 
- Support for logging out of vault to check if seed phrase is correctly saved by user on paper or pen drive. 
- Support to handle multiple vaults 
- Support for recovering multiple wallets using 12 word key phrases.
- Support to easily see AIWA version.

Actual:
- No support to log out of AIWA's current vault. Cannot easily check to see if key phrase has been stored correctly on paper or pen drive.
- Cannot manage multiple vaults in the event that someone is managing wallets of multiple users and wish to save those wallets individually (each user may be able to restore wallet in case manager is unreachable).
- No support for users who wish to import wallets of other users using only 12 word key phrase. 
-- Private key and key store file are not easily saved on paper.
- AIWA version cannot be quickly viewed on menu of the app. Currently have to view Google Chrome's extension section connected to AIWA to see AIWA version.

**Comment by JesseAbram** [comment]
> Support for logging out of vault to check if seed phrase is correctly saved by user on paper or pen drive.

- Allowing logging out of vault is serious as accounts can not be recovered unless mnemonic was written down correctly. This was avoided for new users of Aion to not lose their funds. 

- If user wants to test then they should use different user profiles in [chrome](https://www.pcworld.com/article/2089364/how-to-create-and-manage-multiple-user-profiles-in-chrome.html) 

- Or you can show your seed words in the options 

> Cannot manage multiple vaults in the event that someone is managing wallets of multiple users and wish to save those wallets individually (each user may be able to restore wallet in case manager is unreachable).

- Aiwa is not designed for custodial services it is designed for DApps and DApp interaction our best recommendation is to use multiple user profiles in chrome

- You can import vaults but they will be merged 


> No support for users who wish to import wallets of other users using only 12 word key phrase.
-- Private key and key store file are not easily saved on paper

- This goes agains the design principals of AIWA as it was made for DApp interaction. 

- This can be handled through multiple user profiles on Chrome



> Support to easily see AIWA version.

- Will create a new issue with a feature request

**Comment by JesseAbram** [comment]
> Support to easily see AIWA version.

Move to Issue #28
