### ISSUE TITLE
Cannot send to LAToken Aion addresses

### ISSUE THREAD

**Issue by stevebayerin** [blockxlabs/aiwa#29]
Before filing a new issue, please provide the following information.

#### AIWA version
1.2

#### Installed from Chrome Web Store or Github release?
web store

#### Chrome version?
74.0.3729.131

#### OS and version?
Windows 10 Education Version, last updated on 9/May/2019

#### Which provider are you using?
Mainnet

#### Expected vs actual behaviour
Expected:
-Send to addresses starting with a0 such as addresses generated by the LAToken exchange.

Actual:
- Entering an Aion address of the LAToken exchange starting with a0 reports an error of invalid address.

#### Any additional information or details?

I was able to send AION to a Bitfinex account and from there to LAToken losing around 1.5 AION in the process.

**Comment by JesseAbram** [comment]
Hey, can you add steps to reproduce please, including the address in question.

**Comment by stevebayerin** [comment]
The address I tried to use is:

**Comment by JesseAbram** [comment]
Hey, the address needs a prefixed 0x in front of it. 
0xa06eee07925e77bb40076a0287be4337c7c477d40c3554874f6b1fa0dcddcb0e would work. In general if you ever have any doubts I recommend getting tokens from the [faucet](https://faucets.blockxlabs.com/) and trying things out on the test net first.
