### ISSUE TITLE
AIWA error when generating a signed transaction

### ISSUE THREAD

**Issue by alwaysaugust** [blockxlabs/aiwa#30]
Before filing a new issue, please provide the following information.

#### AIWA version
1.2

#### Installed from Chrome Web Store or Github release?
web store

#### Chrome version?
Version 74.0.3729.169 (Official Build) (64-bit)

#### OS and version?
MacOS 10.14.5

#### Which provider are you using?
Tested with multiple

#### Steps to reproduce
When trying to generate a signed transaction AIWA gives error: "Unable to sign transaction".

Works if no data field is present.

#### Code snippets/screenshots (if not in above questions)
```
var transaction = {
    data: "0xf0a147ada027d25c5c371e8b7feb6bf8d9767e9a34d169c5f310b6a1dc58ec780f38958400000000000000003782dace9d9000000000000000000000000000000000004000000000000000000000000000000000",
    gas: 221000,
    gasPrice: 10000000000,
    nonce: 213,
    timestamp: 1559065474979000,
    to: "0xa0ae5a4854293dd64412327c7c172d911da524fc6f39fc211be7b7ecaac0185f"
}
window.aionweb3.eth.signTransaction(transaction).then((signedTransaction)=>{
    ...
}).catch((error) => {
    ...
})
```
<img width="378" alt="Screen Shot 2019-05-28 at 12 00 59 PM" src="https://user-images.githubusercontent.com/38122173/58499667-a5c39000-814e-11e9-904b-6837497fa2a8.png">

**Comment by dhruvinparikh93** [comment]
Created PR #31 for above issue.

**Comment by alwaysaugust** [comment]
When can we expect this fix to be included into a release build?

**Comment by dhruvinparikh93** [comment]
@alwaysaugust Please use latest [release](https://github.com/blockxlabs/aiwa/releases/tag/v1.3)

**Comment by kushptlapigarage** [comment]
Fixed
