### ISSUE TITLE
Default NRG limit insufficient for ATS token transfer

### ISSUE THREAD

**Issue by a-toad-a-so** [blockxlabs/aiwa#32]
Before filing a new issue, please provide the following information.

#### AIWA version
1.2

#### Installed from Chrome Web Store or Github release?
web store

#### Chrome version?
Version 74.0.3729.157

#### OS and version?
Windows 8.1

#### Which provider are you using?
Mainnet

#### Expected vs actual behaviour
Attempting to send PAY tokens (contract address 0xa0390cff91733550dd3868ff9926aa8cd0dab1ba79d63a35322601dd3e08decd) from AIWA to another wallet (attempted both to another AIWA wallet and a different ATS-compatible wallet (Syna))

Expected - transaction completes

Actual - "OUT_OF_NRG" error (https://mainnet.aion.network/#/transaction/0x00ce9f8a1865712ae96e5b5b02f1c01b96b6ab0467ceed7197ce4076f17bc5be)

More details - NRG limit set to 90k, unable to change. Prior, have been able to do these txs successfully, apparently default limit was either set higher or did not have a limit (example: https://mainnet.aion.network/#/transaction/0xe47e47d152ec6a354bdabb3b3e5268362380f227a42f9e10356b5d853d0f527d)

**Comment by dhruvinparikh93** [comment]
DApps using AIWA can set custom NRGPrice and NRGLimit in the transaction object.
AIWA sets NRGPrice and NRGLimit which is purely based on response from blockchain and AION kernel [if DApp does not supplies them]

DApp can use keys :`gas`  and `gasPrice`  for passing custom NRGLimit and NRGPrice while creating transaction object.

Please find the below code snippets for your ready reference:

- *option 1* : Token transfer with default NRGPrice and NRGLimit
```
aionweb3.eth.contract(abi_of_contract).at(contract_address).transfer(recipient_address,token_amount)
```

- *option 2* : Token transfer with custom NRGPrice and NRGLImit
```
const data = aioweb3.eth.contract(abi_of_contract).at(contract_address).transfer.getData(recipient_address,token_amount);
aionweb3.eth.sendTransaction({to:"contract_address",gas:"custom_NRGLimit",gasPrice:"custom_NRGPrice",data:data})
```

**Comment by kushptlapigarage** [comment]
Closing the issue due to inactivity.
