### ISSUE TITLE
Token balance not showing correctly

### ISSUE THREAD

**Issue by jonathanjm** [blockxlabs/aiwa#4]
![screen shot 2018-11-08 at 12 54 02 pm](https://user-images.githubusercontent.com/3130843/48217514-91a47680-e355-11e8-951e-78fd1a6b9177.png)

**Comment by hamzahayat** [comment]
@jonathanjm What is that balance supposed to be?

**Comment by hamzahayat** [comment]
@jonathanjm Not sure why you're seeing that. The token that I deployed on Mastery was with the default decimals (18), and it displays the right balance. Can I ask what the granularity and decimals was for the token that you deployed?

**Comment by jonathanjm** [comment]
Granularity 1 and decimals default 18. I tested this on our local chain. I'll test on Mastery and let you know.

**Comment by hamzahayat** [comment]
This issue has now been resolved. 

For future reference, please read through the [AIP-4](https://github.com/aionnetwork/AIP/issues/4) standards when deploying a token on Aion. More specifically [this comment](https://github.com/aionnetwork/AIP/issues/4#issuecomment-442243388) related to the `totalSupply` of the token during deployment.

**Comment by jonpurdy-blockxlabs** [comment]
This should be fixed in [release 0.4](url
https://github.com/blockxlabs/aiwa/tree/0.4). Please reopen if still an issue.
