### ISSUE TITLE
aionweb3.accounts undefined on load

### ISSUE THREAD

**Issue by jonathanjm** [blockxlabs/aiwa#5]
On page load, aionweb3.accounts is undefined, I have to create a new wallet or switch wallets to get a value in aionweb3.accounts.

**Comment by jonathanjm** [comment]
I tried that too but same problem.

With the latest release the issue is different, it gets the accounts when I click to open Aiwa.

Not sure if this is an issue or it's supposed to work that way.

**Comment by dhruvinparikh** [comment]
Thank you for exact description. This is internally addressed and you would find it working as expected in future releases.

Thanks
Dhruvin

**Comment by jonpurdy-blockxlabs** [comment]
This is fixed in [release 0.4](url
https://github.com/blockxlabs/aiwa/tree/0.4).
