### ISSUE TITLE
Transaction confirmation popup hangs on confirm.

### ISSUE THREAD

**Issue by ToJen** [blockxlabs/aiwa#7]
I attempted to send a transaction from a dApp and the `Send` button did not respond in the popup displayed. I have confirmed on the Mastery block explorer that the transaction was not sent.

cc: @arjitkhullar

[![aiwa-frozen.png](https://i.postimg.cc/KY4MrKf3/aiwa-frozen.png)](https://postimg.cc/Z9tnJ51J)

**Comment by dhruvinparikh** [comment]
> I attempted to send a transaction from a dApp and the `Send` button did not respond in the popup displayed. I have confirmed on the Mastery block explorer that the transaction was not sent.
> 
> cc: @arjitkhullar
> 
> [![aiwa-frozen.png](https://camo.githubusercontent.com/15643ad13d219d1f193085056c69cd39b586b0bb/68747470733a2f2f692e706f7374696d672e63632f4b59344d724b66332f616977612d66726f7a656e2e706e67)](https://postimg.cc/Z9tnJ51J)

Can you provide steps to reproduce this issue?

Regards
Dhruvin

**Comment by jonpurdy-blockxlabs** [comment]
@ToJen I suspect that this has been corrected in [release 0.4](https://github.com/blockxlabs/aiwa/releases/tag/0.4). I'm going to close it, but please reopen if this is still an issue.

**Comment by ToJen** [comment]
Looks like it's fixed now thanks. Tested on the [Titan IDE](https://ide.titan-suite.com).

**Comment by dhruvinparikh** [comment]
@ToJen Thanks for heads up.
